baseURL = "http://unwrappedsoftware.com/"
languageCode = "pl-PL"
title = "such wow"
theme = "ananke"
publishDir = "docs"

[[menu.main]]
    name = "Home"
    weight = -100
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Blog"
    weight = -10
    identifier = "blog"
    url = "/blog/"
